### ISSUE TITLE
Could you provide the training recipe of the ResNet50-SlowOnly baseline?

### ISSUE THREAD

**Issue by sebgao** [BannyStone/Video_Classification_PyTorch#2]
Hi, thanks for the great work.

I plan to reproduce the result of the ResNet50-SlowOnly baseline. I'm wondering whether the training recipe is indeed `scripts/kinetics400_3d_res50_slowonly_im_pre.sh`?

**Comment by sebgao** [comment]
Does the validation scrore (73.77 and 91.17) of the baseline include TSN testing, that is, TSN+3D?

**Comment by BannyStone** [comment]
Yes, the training script is indeed scripts/kinetics400_3d_res50_slowonly_im_pre.sh
The validation procedure follows Non-Local Neural Network, i.e., fusing scores from 30 crops (3crop/clip * 10clips).

**Comment by sebgao** [comment]
Thanks a lot for clarification.
